### ISSUE TITLE
Can't use TDigestUDT in spark UDF to get cdf 

### ISSUE THREAD

**Issue by pwebbitrs** [isarn/isarn-sketches-spark#19]
I am currently using TDigests to obtain cdf and inverse cdfs.  I have a DataFrame that now contains TDigests via TDigestSQL. However i want to be able to get back the CDF etc via the Spark SQL DSL api. 

So to do that I am using this:

```
  val tDigestCdf: UserDefinedFunction =
    UserDefinedFunction(getCDFFromTDigest _, DoubleType, Some(Seq(TDigestUDT, DoubleType)))
      .withName("getCDFFromTDigest")

  def getCDFFromTDigest(tdigestsql: TDigestSQL, percent: Double): Double = {
    tdigestsql.tdigest.cdf(percent)
  }
```
Then to use this i do:
```
 dataFrame.select(  tDigestCdf(col("mydigest))  )
```
But unfortunately i am then getting this error:
```
Wrapped by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.ClassCastException: MySparkFunctions$$anonfun$3 cannot be cast to scala.Function1
org.apache.spark.sql.catalyst.expressions.ScalaUDF.<init>(ScalaUDF.scala:98)
org.apache.spark.sql.expressions.UserDefinedFunction.apply(UserDefinedFunction.scala:71)

```

Should it be possible to use the provided UDT in this fashion? I read something about UDT's not being exposed any more but that seems a bit weird to me.

**Comment by pwebbitrs** [comment]
Embarrassingly i have noticed this is just me not passing in the second parameter when calling the UDF.  I have now got this working nicely. 

```
dataFrame.select( tDigestCdf(col(expansion._1), new Column(Literal(0.95))))
```
Closing as this is not a bug or an issue.

**Comment by erikerlandson** [comment]
You solved it before I saw your issue :D
