### ISSUE TITLE
TDigestSQL results from the TDigestUDAF cannot themselves be aggregated in Spark SQL.

### ISSUE THREAD

**Issue by johnwhumphreys** [isarn/isarn-sketches-spark#4]
I had second-level data aggregated to minute level using a TDigest, and wanted to further aggregate the persisted data frame to hour level and could not do so as there is no way to aggregate the TDigestSQL objects themselves in an aggregate function in Spark SQL.

To work around this, I copied and tweaked the TDigestUDAF which allowed me to aggregate TDigestSQL instances resulting from the first TDigestUDAF.  Using this, you can get as high level as you need, re-aggregating the TDigest results.

```case class TDigestSQLAggUDAF(deltaV: Double, maxDiscreteV: Int) extends UserDefinedAggregateFunction {

  // A t-digest is deterministic, but it is only statistically associative or commutative
  // and spark will merge partition results in nondeterministic order. That makes
  // the result of the aggregation statistically "deterministic" but not strictly so.
  def deterministic: Boolean = false

  def inputSchema: StructType = StructType(StructField("tdigest", TDigestUDT) :: Nil)

  def bufferSchema: StructType = StructType(StructField("tdigest", TDigestUDT) :: Nil)

  def dataType: DataType = TDigestUDT

  def initialize(buf: MutableAggregationBuffer): Unit = {
    buf(0) = TDigestSQL(TDigest.empty(deltaV, maxDiscreteV))
  }

  //Since every value will be a TDigestSQL, update acts just like merge and combines TDigestSQL
  //objects by combining their inner TDigests.
  def update(buf: MutableAggregationBuffer, input: Row): Unit = {
    if (!input.isNullAt(0)) {
      buf(0) = TDigestSQL(buf.getAs[TDigestSQL](0).tdigest ++ input.getAs[TDigestSQL](0).tdigest)
    }
  }

  def merge(buf1: MutableAggregationBuffer, buf2: Row): Unit = {
    buf1(0) = TDigestSQL(buf1.getAs[TDigestSQL](0).tdigest ++ buf2.getAs[TDigestSQL](0).tdigest)
  }

  def evaluate(buf: Row): Any = buf.getAs[TDigestSQL](0)
}
```

Might be a useful addition to the library; though you may have a better way of achieving the same :).

**Comment by erikerlandson** [comment]
Thanks @w00te, I will integrate this into the package!

**Comment by erikerlandson** [comment]
@johnwhumphreys I added t-digest aggregators (reducers) `TDigestReduceUDAF` and `TDigestArrayReduceUDAF`, they will land in my next release:

https://github.com/erikerlandson/isarn-sketches-spark/blob/feature/pyspark/src/main/scala/org/isarnproject/sketches/udaf/TDigestUDAF.scala#L232

**Comment by johnwhumphreys** [comment]
Awesome :) thank you for pulling that in!

Still have yet to try the parquet serialization fix you suggested; but it's
in my notes for later when I have time to go back to that.  Using the
object file serialization for the moment as you provided earlier.

**Comment by erikerlandson** [comment]
I'll optimistically close this in anticipation of merging for upcoming release
